//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDividendTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart_Dividend_Portfolio_Tracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Asset.
        /// </summary>
        public static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Investment.
        /// </summary>
        public static string CalcInitial {
            get {
                return ResourceManager.GetString("CalcInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPOUND INTEREST MAGIC.
        /// </summary>
        public static string CalcMenuTitle {
            get {
                return ResourceManager.GetString("CalcMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Contribution.
        /// </summary>
        public static string CalcMonthly {
            get {
                return ResourceManager.GetString("CalcMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Interest Calculator.
        /// </summary>
        public static string CalcOpt {
            get {
                return ResourceManager.GetString("CalcOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Annual Yield (%).
        /// </summary>
        public static string CalcRate {
            get {
                return ResourceManager.GetString("CalcRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Period (Years).
        /// </summary>
        public static string CalcYears {
            get {
                return ResourceManager.GetString("CalcYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to cancel.
        /// </summary>
        public static string CancelHint {
            get {
                return ResourceManager.GetString("CancelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Experience Level.
        /// </summary>
        public static string ChangeExp {
            get {
                return ResourceManager.GetString("ChangeExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Investment Horizon.
        /// </summary>
        public static string ChangeHorizon {
            get {
                return ResourceManager.GetString("ChangeHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner&apos;s Cheat Sheet.
        /// </summary>
        public static string CheatSheetOpt {
            get {
                return ResourceManager.GetString("CheatSheetOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action canceled. Your portfolio remains completely safe..
        /// </summary>
        public static string ClearCanceled {
            get {
                return ResourceManager.GetString("ClearCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Type YES to confirm: .
        /// </summary>
        public static string ClearConfirm {
            get {
                return ResourceManager.GetString("ClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Entire Portfolio.
        /// </summary>
        public static string ClearPortfolio {
            get {
                return ResourceManager.GetString("ClearPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Interest Calculator.
        /// </summary>
        public static string CompoundCalc {
            get {
                return ResourceManager.GetString("CompoundCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education hub.
        /// </summary>
        public static string EduMenuTitle {
            get {
                return ResourceManager.GetString("EduMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your portfolio is empty. Add some assets first!.
        /// </summary>
        public static string EmptyPort {
            get {
                return ResourceManager.GetString("EmptyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter target date (dd.MM.yyyy, default +10 years): .
        /// </summary>
        public static string EnterEndDate {
            get {
                return ResourceManager.GetString("EnterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expected inflation (%, default 3%): .
        /// </summary>
        public static string EnterInflation {
            get {
                return ResourceManager.GetString("EnterInflation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your monthly contribution ($): .
        /// </summary>
        public static string EnterMonthly {
            get {
                return ResourceManager.GetString("EnterMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter P/E Ratio: .
        /// </summary>
        public static string EnterPE {
            get {
                return ResourceManager.GetString("EnterPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Average Price ($): .
        /// </summary>
        public static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expected annual return (%, default 8%): .
        /// </summary>
        public static string EnterRate {
            get {
                return ResourceManager.GetString("EnterRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity of Shares: .
        /// </summary>
        public static string EnterShares {
            get {
                return ResourceManager.GetString("EnterShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter stock ticker.
        /// </summary>
        public static string EnterTicker {
            get {
                return ResourceManager.GetString("EnterTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Dividend Yield (%): .
        /// </summary>
        public static string EnterYield {
            get {
                return ResourceManager.GetString("EnterYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving progress... See you later, Investor!.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner (Just starting).
        /// </summary>
        public static string ExpBeginner {
            get {
                return ResourceManager.GetString("ExpBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your investment experience?.
        /// </summary>
        public static string ExpLevel {
            get {
                return ResourceManager.GetString("ExpLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced.
        /// </summary>
        public static string ExpPro {
            get {
                return ResourceManager.GetString("ExpPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     PLAN CALCULATIONS                      .
        /// </summary>
        public static string GoalCalcHeader {
            get {
                return ResourceManager.GetString("GoalCalcHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cost in {0} years (2.14% inflation):.
        /// </summary>
        public static string GoalCostFuture {
            get {
                return ResourceManager.GetString("GoalCostFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cost today:.
        /// </summary>
        public static string GoalCostToday {
            get {
                return ResourceManager.GetString("GoalCostToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Cancel Action ].
        /// </summary>
        public static string GoalDelCancel {
            get {
                return ResourceManager.GetString("GoalDelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You have no saved goals to delete..
        /// </summary>
        public static string GoalDelEmpty {
            get {
                return ResourceManager.GetString("GoalDelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a financial goal to delete:.
        /// </summary>
        public static string GoalDelPrompt {
            get {
                return ResourceManager.GetString("GoalDelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///✔ Goal &quot;{0}&quot; has been successfully removed!.
        /// </summary>
        public static string GoalDelSuccess {
            get {
                return ResourceManager.GetString("GoalDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Growth.
        /// </summary>
        public static string GoalGrowth {
            get {
                return ResourceManager.GetString("GoalGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               HOW THE GOAL PLANNING WORKS                  .
        /// </summary>
        public static string GoalHowItWorks {
            get {
                return ResourceManager.GetString("GoalHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your main investment goal (e.g., Passive Income): .
        /// </summary>
        public static string GoalInfo {
            get {
                return ResourceManager.GetString("GoalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved goals yet. Calculate one in option 1!.
        /// </summary>
        public static string GoalListEmpty {
            get {
                return ResourceManager.GetString("GoalListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                         MY SAVED FINANCIAL GOALS                                    .
        /// </summary>
        public static string GoalListHeader {
            get {
                return ResourceManager.GetString("GoalListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   🎯 FINANCIAL GOAL MANAGER.
        /// </summary>
        public static string GoalMenuHeader {
            get {
                return ResourceManager.GetString("GoalMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Calculate and save a new goal.
        /// </summary>
        public static string GoalMenuOpt1 {
            get {
                return ResourceManager.GetString("GoalMenuOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. View my saved goals.
        /// </summary>
        public static string GoalMenuOpt2 {
            get {
                return ResourceManager.GetString("GoalMenuOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Delete a financial goal.
        /// </summary>
        public static string GoalMenuOpt3 {
            get {
                return ResourceManager.GetString("GoalMenuOpt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Back to Main Menu.
        /// </summary>
        public static string GoalMenuOpt4 {
            get {
                return ResourceManager.GetString("GoalMenuOpt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name your goal (e.g. Apartment).
        /// </summary>
        public static string GoalNamePrompt {
            get {
                return ResourceManager.GetString("GoalNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       NEW GOAL PLAN                        .
        /// </summary>
        public static string GoalNewPlanHeader {
            get {
                return ResourceManager.GetString("GoalNewPlanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive Income.
        /// </summary>
        public static string GoalPassive {
            get {
                return ResourceManager.GetString("GoalPassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to start calculating your own goal....
        /// </summary>
        public static string GoalPressAnyCalc {
            get {
                return ResourceManager.GetString("GoalPressAnyCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Current cost of your goal ($).
        /// </summary>
        public static string GoalPricePrompt {
            get {
                return ResourceManager.GetString("GoalPricePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your main investment goal.
        /// </summary>
        public static string GoalPrompt {
            get {
                return ResourceManager.GetString("GoalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Purchase (Real estate, etc.).
        /// </summary>
        public static string GoalPurchase {
            get {
                return ResourceManager.GetString("GoalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Expected annual return (%).
        /// </summary>
        public static string GoalRatePrompt {
            get {
                return ResourceManager.GetString("GoalRatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: &apos;Passive Income&apos; goal was removed because it&apos;s too risky for a &lt;5 years horizon..
        /// </summary>
        public static string GoalRemovedWarning {
            get {
                return ResourceManager.GetString("GoalRemovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➜ REQUIRED MONTHLY INVESTMENT:.
        /// </summary>
        public static string GoalReqInv {
            get {
                return ResourceManager.GetString("GoalReqInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Calculation finished without saving..
        /// </summary>
        public static string GoalSavedCancel {
            get {
                return ResourceManager.GetString("GoalSavedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///✔ Goal saved successfully!.
        /// </summary>
        public static string GoalSavedSuccess {
            get {
                return ResourceManager.GetString("GoalSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///💾 Do you want to save this goal to your profile? (YES/NO): .
        /// </summary>
        public static string GoalSavePrompt {
            get {
                return ResourceManager.GetString("GoalSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use a standard 2.14% annual inflation rate for the USD..
        /// </summary>
        public static string GoalStep1Desc {
            get {
                return ResourceManager.GetString("GoalStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌 Step 1. Find the &apos;real&apos; cost through the years (with inflation).
        /// </summary>
        public static string GoalStep1Title {
            get {
                return ResourceManager.GetString("GoalStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We divide the future cost by the compound interest factor..
        /// </summary>
        public static string GoalStep2Desc {
            get {
                return ResourceManager.GetString("GoalStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌 Step 2. Calculate your monthly investment target.
        /// </summary>
        public static string GoalStep2Title {
            get {
                return ResourceManager.GetString("GoalStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 Goal:.
        /// </summary>
        public static string GoalTarget {
            get {
                return ResourceManager.GetString("GoalTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Target horizon (years).
        /// </summary>
        public static string GoalYearsPrompt {
            get {
                return ResourceManager.GetString("GoalYearsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string GoalYearsWord {
            get {
                return ResourceManager.GetString("GoalYearsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an investment portfolio?.
        /// </summary>
        public static string HasPort {
            get {
                return ResourceManager.GetString("HasPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 10 years.
        /// </summary>
        public static string Horiz10 {
            get {
                return ResourceManager.GetString("Horiz10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 5 years.
        /// </summary>
        public static string Horiz5 {
            get {
                return ResourceManager.GetString("Horiz5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 10 years.
        /// </summary>
        public static string HorizMore {
            get {
                return ResourceManager.GetString("HorizMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your investment horizon.
        /// </summary>
        public static string HorizonPrompt {
            get {
                return ResourceManager.GetString("HorizonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Real Value shows your purchasing power in TODAY&apos;S money..
        /// </summary>
        public static string InflationNote {
            get {
                return ResourceManager.GetString("InflationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format or date in the past. Use dd.MM.yyyy.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a valid number..
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Invested.
        /// </summary>
        public static string Invested {
            get {
                return ResourceManager.GetString("Invested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Portfolio.
        /// </summary>
        public static string MenuOpt1 {
            get {
                return ResourceManager.GetString("MenuOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner&apos;s Cheat Sheet.
        /// </summary>
        public static string MenuOpt2 {
            get {
                return ResourceManager.GetString("MenuOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuOpt3 {
            get {
                return ResourceManager.GetString("MenuOpt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string MenuOpt4 {
            get {
                return ResourceManager.GetString("MenuOpt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Calculator.
        /// </summary>
        public static string MenuOpt5 {
            get {
                return ResourceManager.GetString("MenuOpt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Milestone Calculator.
        /// </summary>
        public static string MenuOptGoalCalc {
            get {
                return ResourceManager.GetString("MenuOptGoalCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Value.
        /// </summary>
        public static string NominalValue {
            get {
                return ResourceManager.GetString("NominalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio has been completely cleared!.
        /// </summary>
        public static string PortfolioCleared {
            get {
                return ResourceManager.GetString("PortfolioCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTFOLIO MANAGEMENT.
        /// </summary>
        public static string PortfolioMenu {
            get {
                return ResourceManager.GetString("PortfolioMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to continue....
        /// </summary>
        public static string PressEnter {
            get {
                return ResourceManager.GetString("PressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved successfully! Let&apos;s start..
        /// </summary>
        public static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Value.
        /// </summary>
        public static string RealValue {
            get {
                return ResourceManager.GetString("RealValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Asset.
        /// </summary>
        public static string RemoveStock {
            get {
                return ResourceManager.GetString("RemoveStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tutorial.
        /// </summary>
        public static string ResetTutorial {
            get {
                return ResourceManager.GetString("ResetTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Discretionary.
        /// </summary>
        public static string SecDiscretionary {
            get {
                return ResourceManager.GetString("SecDiscretionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string SecEnergy {
            get {
                return ResourceManager.GetString("SecEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financials.
        /// </summary>
        public static string SecFinance {
            get {
                return ResourceManager.GetString("SecFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare.
        /// </summary>
        public static string SecHealth {
            get {
                return ResourceManager.GetString("SecHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrials.
        /// </summary>
        public static string SecIndustrials {
            get {
                return ResourceManager.GetString("SecIndustrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string SecMaterials {
            get {
                return ResourceManager.GetString("SecMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string SecRealEstate {
            get {
                return ResourceManager.GetString("SecRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Staples.
        /// </summary>
        public static string SecStaples {
            get {
                return ResourceManager.GetString("SecStaples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string SecTech {
            get {
                return ResourceManager.GetString("SecTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string SecUtilities {
            get {
                return ResourceManager.GetString("SecUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language.
        /// </summary>
        public static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sector.
        /// </summary>
        public static string SelectSector {
            get {
                return ResourceManager.GetString("SelectSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an asset to remove.
        /// </summary>
        public static string SelectToRemove {
            get {
                return ResourceManager.GetString("SelectToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Investment Goals.
        /// </summary>
        public static string SetGoals {
            get {
                return ResourceManager.GetString("SetGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE SETTINGS.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset successfully added to portfolio!.
        /// </summary>
        public static string StockAdded {
            get {
                return ResourceManager.GetString("StockAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset successfully removed!.
        /// </summary>
        public static string StockRemoved {
            get {
                return ResourceManager.GetString("StockRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div/Yr.
        /// </summary>
        public static string TblAnnualDiv {
            get {
                return ResourceManager.GetString("TblAnnualDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Price.
        /// </summary>
        public static string TblFuturePrice {
            get {
                return ResourceManager.GetString("TblFuturePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Name.
        /// </summary>
        public static string TblGoalName {
            get {
                return ResourceManager.GetString("TblGoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Inv.
        /// </summary>
        public static string TblMonthlyInv {
            get {
                return ResourceManager.GetString("TblMonthlyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TblPrice {
            get {
                return ResourceManager.GetString("TblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Today.
        /// </summary>
        public static string TblPriceToday {
            get {
                return ResourceManager.GetString("TblPriceToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string TblReturn {
            get {
                return ResourceManager.GetString("TblReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string TblSector {
            get {
                return ResourceManager.GetString("TblSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string TblShares {
            get {
                return ResourceManager.GetString("TblShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string TblTicker {
            get {
                return ResourceManager.GetString("TblTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value.
        /// </summary>
        public static string TblValue {
            get {
                return ResourceManager.GetString("TblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string TblYears {
            get {
                return ResourceManager.GetString("TblYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield.
        /// </summary>
        public static string TblYield {
            get {
                return ResourceManager.GetString("TblYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Annual Dividend Income:.
        /// </summary>
        public static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio Value.
        /// </summary>
        public static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome! You are ready. Let&apos;s go to the Main Menu..
        /// </summary>
        public static string TutReady {
            get {
                return ResourceManager.GetString("TutReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial status has been reset! It will launch on next restart..
        /// </summary>
        public static string TutResetSuccess {
            get {
                return ResourceManager.GetString("TutResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing is like planting a tree. The earlier you start, the bigger it grows..
        /// </summary>
        public static string TutStep1 {
            get {
                return ResourceManager.GetString("TutStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, future investor! Let&apos;s start your financial journey..
        /// </summary>
        public static string TutWelcome {
            get {
                return ResourceManager.GetString("TutWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Assets.
        /// </summary>
        public static string ViewAssets {
            get {
                return ResourceManager.GetString("ViewAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sector Chart.
        /// </summary>
        public static string ViewSectorChart {
            get {
                return ResourceManager.GetString("ViewSectorChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Smart Dividend Tracker AI!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
